name: workflowcall
on: 
  workflow_call:
    inputs:
      myvar:
        required: true
        type: string
        default: yash
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{  inputs.myvar }}"
