name: Context
on: [issues,workflow_dispatch]
env:
  var1: hello

jobs:
  context:
    outputs:
      myvar: ${{ steps.step1.outputs.test }}
    runs-on: ubuntu-latest
    steps:
    - name: PRINT DETAILS
      run: echo "${{ toJson(github.event) }}"
    - name: set variable value for ouput
      id: step1
      run: |
        echo "test=hello" >> "$GITHUB_OUTPUT"
        echo "action_state=yellow" >> "$GITHUB_ENV"
        echo "$var1"
        echo "${{ secrets.MYPASS }}"
        echo "${{ vars.yash }}"
    - run: echo "$action_state"
  printout:
    environment: test
    needs: context
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: print value
      run: |
         ls
         #ls D:\a\GithubaActions\GithubaActions\github\workflows
         echo "${{  needs.context.outputs.myvar }}"
         echo ${{ secrets.mysecret }}
    - uses: ./github/workflows
      with:
        who-to-greet: Yash


  reusable:

    uses: ./.github/workflows/callme.yml
    with:
      myvar: noyash

     

